CREATE DATABASE IF NOT EXISTS suzuhara_media DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE suzuhara_media;
CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, username VARCHAR(64) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role VARCHAR(32) NOT NULL DEFAULT 'viewer', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS albums (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, title VARCHAR(160) NOT NULL, visibility VARCHAR(32) NOT NULL DEFAULT 'private', owner_id BIGINT UNSIGNED NULL);
CREATE TABLE IF NOT EXISTS media (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, title VARCHAR(255) NULL, media_type VARCHAR(32) NOT NULL, storage_path TEXT NOT NULL, album_id BIGINT UNSIGNED NULL);
